const form = document.getElementById('my-form');
const userList = document.getElementById('users'); //ul
const errorMessage = document.querySelector('.err-msg');

//store user details
function storeUserDetails(e){
    e.preventDefault();
    //get userName, userEmail, user phone number inputs and store them in an user object
    const userObj ={
        name: document.getElementById('name').value.trim(), //userName
        email: document.getElementById('email').value.trim(), //userEmail
        phoneNumber: document.getElementById('phoneNumber').value //user phone number
    };
    //add the user to crudcrud.com
    axios
    .post("https://crudcrud.com/api/bce6166f4e3541499c70cc5a8f2418fc/appointmentData",userObj)
    .then((response) => {
        displayUser(response.data);
        //clear the input fields if the user is successfully submitted to crudcrud.com
        document.getElementById('name').value = '';
        document.getElementById('email').value = '';
        document.getElementById('phoneNumber').value = '';
    })
    .catch((err) => {
        console.log(err);
        displayError();
    });
}

//delete user details
function deleteUserDetails(e){
    //find the li whose delete button is clicked
    const li = e.target.parentElement;
    //remove the user from crudcrud.com
    axios
    .delete("https://crudcrud.com/api/bce6166f4e3541499c70cc5a8f2418fc/appointmentData/" + li.id)
    .then(() => { 
        //remove the user from the displayed list
        userList.removeChild(li);
    })
    .catch((err) => {
        console.log(err);
        displayError();
    });
}

//display all the users stored in crudcrud.com when webpage is reloaded
function displayAllUsers(){
    axios
    .get("https://crudcrud.com/api/bce6166f4e3541499c70cc5a8f2418fc/appointmentData")
    .then((response) => {
        response.data.forEach((userObj) => {
            displayUser(userObj);
        });
    })
    .catch((err) => {
        console.log(err);
        displayError();
    });
}

//display user stored in crudcrud.com based on the user object passed
function displayUser(userObj){
    //create new list item
    const li = document.createElement('li');
    //set the class of li 
    li.className = 'item';
    //the id of li must be the same as _id (generated by crudcrud.com) of userObj
    li.id = userObj._id;
    //append textnode with the value of userName, userEmail, user phone number to li
    li.appendChild(document.createTextNode(userObj.name + ' : ' + userObj.email + ' : ' + userObj.phoneNumber));
    
    //create edit button
    const editBtn = document.createElement('button');
    //set the class of edit button
    editBtn.className = 'edit';
    //append textnode to edit button
    editBtn.appendChild(document.createTextNode('Edit'));
    //append edit button to li
    li.appendChild(editBtn);

    //create delete button
    const deleteBtn = document.createElement('button');
    //set the class of delete button
    deleteBtn.className = 'delete';
    //add event listener on delete button
    deleteBtn.addEventListener('click', deleteUserDetails);
    //append textnode to delete button
    deleteBtn.appendChild(document.createTextNode('Delete'));
    //append delete button to li
    li.appendChild(deleteBtn);

    //append li to ul
    userList.appendChild(li);
}

//displays error message in DOM
function displayError(){
    //create a new h4 element
    const err = document.createElement('h4');
    //add error message text to the h4 element
    err.appendChild(document.createTextNode('Error: something went wrong :('));
    //append the h4 to error message
    errorMessage.appendChild(err);
    //error message disappears after 3000ms
    setTimeout(() => { errorMessage.innerHTML = '' }, 3000);
}

/* EVENT LISTENERS */

//display all users event
window.addEventListener('DOMContentLoaded',displayAllUsers);
//Form submit event
form.addEventListener('submit',storeUserDetails);
